# Generated by Django 5.2.13 on 2026-09-14 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_blob', models.CharField(blank=True, max_length=1024)),
                ('size_bytes', models.PositiveIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('source_label', models.CharField(default='Anonymized test contract', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_record_code', models.CharField(max_length=80)),
                ('record_code', models.CharField(max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='core.contractdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Extracting'), ('completed', 'Ready for review'), ('failed', 'Needs attention')], default='queued', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.contractdocument')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value', models.TextField()),
                ('page', models.PositiveIntegerField()),
                ('quote', models.TextField()),
                ('review_status', models.CharField(choices=[('pending', 'Unreviewed extraction'), ('confirmed', 'Reviewed extraction'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.extractionrun')),
            ],
            options={
                'ordering': ['name', 'page', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('origin', models.CharField(choices=[('synthetic', 'Synthetic demo'), ('document', 'Document-backed')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_records', to='core.asset')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.leaserecord'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('document',), name='one_active_extraction_per_document'),
        ),
    ]
