# Generated by Django 5.2.13 on 2026-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_field_sources_contractdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationevent',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='associationevent',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='association_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='association_status',
            field=models.CharField(choices=[('pending', 'Awaiting extraction'), ('review', 'Needs location review'), ('automatic', 'Linked automatically'), ('manual', 'Linked manually'), ('outside', 'Reviewed · outside portfolio')], db_index=True, default='pending', max_length=20),
        ),
    ]
