# Generated by Django 5.2.13 on 2026-09-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contract_location_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('resident_name', models.CharField(max_length=120)),
                ('received_on', models.DateField(db_index=True)),
                ('channel', models.CharField(default='Resident interview', max_length=40)),
                ('recommendation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transcript', models.TextField()),
                ('origin', models.CharField(choices=[('synthetic', 'Generated'), ('resident', 'Resident supplied')], default='synthetic', max_length=20)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('analysis_status', models.CharField(choices=[('pending', 'Awaiting analysis'), ('processing', 'Analyzing'), ('completed', 'Analyzed'), ('failed', 'Needs analysis')], db_index=True, default='pending', max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('analysis_model', models.CharField(blank=True, max_length=100)),
                ('analysis_version', models.CharField(blank=True, max_length=40)),
                ('analysis_input_hash', models.CharField(blank=True, max_length=64)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_error', models.CharField(blank=True, max_length=240)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_feedback', to='core.asset')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leaserecord')),
            ],
            options={
                'ordering': ['-received_on', 'reference'],
                'constraints': [models.CheckConstraint(condition=models.Q(('recommendation_score__isnull', True), models.Q(('recommendation_score__gte', 0), ('recommendation_score__lte', 10)), _connector='OR'), name='feedback_recommendation_0_to_10')],
            },
        ),
    ]
